<a href="https://colab.research.google.com/github/puja-verma11/data-transformation/blob/main/working_with_numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = '/content/drive/My Drive/Colab Notebooks/adult.csv'
sales_data = pd.read_csv(file_path)
print("First 5 rows of the dataset:")
display(sales_data.head())

display("\nDataset info:")
sales_data.info()

#Read the dataset from the CSV file and clean the data — remove all rows containing the "?" character in any column.
sales_data = sales_data.replace('?', pd.NA)
sales_data = sales_data.dropna()

#Also, verify the correctness of the data (salary and salary in $K).
display(sales_data)

#Display the number of men and women in the dataset.
display("Number of men and women in the dataset:")
display(sales_data['sex'].value_counts())

#Find the average age of men in the dataset.
display("Average age of men in the dataset:")
display(sales_data[sales_data['sex'] == 'Male']['age'].mean())


#Calculate the percentage of people from Poland (native-country).
display("Percentage of people from Poland (native-country):")
display((sales_data[sales_data['native-country'] == 'Poland'].shape[0] / sales_data.shape[0]) * 100)

#Check if there are people without higher education (education: Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters, Doctorate) but earning > 50K.
display("People without higher education but earning > 50K:")
display(sales_data[(sales_data['education'] != 'Bachelors') &
 (sales_data['education'] != 'Prof-school')])

#Obtain age statistics for each education type. Use groupby and describe for this.
display("Age statistics for each education type:")
display(sales_data.groupby('education')['age'].describe())


#Compare the salaries of married and unmarried men. Who earns more? (> 50K or <= 50K) Married men are those whose marital-status starts with Married. Others are considered unmarried.
display("Salaries of married and unmarried men:")
display(sales_data[(sales_data['sex'] == 'Male') & (sales_data['marital-status'].str.startswith('Married'))]['salary'].value_counts())


#Find the maximum number of hours a person works per week. How many people work this many hours per week?
display("Maximum number of hours a person works per week:")
display(sales_data['hours-per-week'].max())



# Read the dataset from the CSV file and clean the data — remove all rows containing the "?" character in any column.
sales_data = sales_data.replace('?', pd.NA)
sales_data = sales_data.dropna()
display(sales_data)


#Calculate the mean and standard deviation of the age for people earning > 50K per year. Then, calculate the same for those earning <= 50K.

sales_data['salary'] = sales_data['salary'].str.strip()

age_stats = sales_data.groupby('salary')['age'].agg(['mean', 'std'])

print("Mean and standard deviation of age:")
print(">50K:")
print("Mean:", age_stats.loc['>50K', 'mean'])
print("Std:", age_stats.loc['>50K', 'std'])

print("\n<=50K:")
print("Mean:", age_stats.loc['<=50K', 'mean'])
print("Std:", age_stats.loc['<=50K', 'std'])

Mounted at /content/drive
First 5 rows of the dataset:

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
0,0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K,39
1,1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K,35
2,2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K,27
3,3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K,43
4,4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K,25

'\nDataset info:'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      32561 non-null  int64
 1   age             32561 non-null  int64
 2   workclass       32561 non-null  object
 3   education       32561 non-null  object
 4   marital-status  32561 non-null  object
 5   occupation      32561 non-null  object
 6   relationship    32561 non-null  object
 7   race            32561 non-null  object
 8   sex             32561 non-null  object
 9   hours-per-week  32561 non-null  int64
 10  native-country  32561 non-null  object
 11  salary          32561 non-null  object
 12  salary K$       32561 non-null  int64
dtypes: int64(4), object(9)
memory usage: 3.2+ MB

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
0,0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K,39
1,1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K,35
2,2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K,27
3,3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K,43
4,4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,32556,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,38,United-States,<=50K,36
32557,32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,>50K,173
32558,32558,58,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,40,United-States,<=50K,40
32559,32559,22,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,20,United-States,<=50K,38
32560,32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,>50K,243

'Number of men and women in the dataset:'

sex
Male      20380
Female     9782
Name: count, dtype: int64

'Average age of men in the dataset:'

np.float64(39.18400392541707)

'Percentage of people from Poland (native-country):'

0.18566408063125786

'People without higher education but earning > 50K:'

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
2,2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K,27
3,3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K,43
5,5,37,Private,Masters,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,<=50K,44
6,6,49,Private,9th,Married-spouse-absent,Other-service,Not-in-family,Black,Female,16,Jamaica,<=50K,49
7,7,52,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,45,United-States,>50K,307
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,32556,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,38,United-States,<=50K,36
32557,32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,>50K,173
32558,32558,58,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,40,United-States,<=50K,40
32559,32559,22,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,20,United-States,<=50K,38
32560,32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,>50K,243

'Age statistics for each education type:'

               count       mean        std   min   25%   50%   75%   max
education
10th           820.0  37.897561  16.225795  17.0  23.0  36.0  52.0  90.0
11th          1048.0  32.363550  15.089307  17.0  18.0  28.5  43.0  90.0
12th           377.0  32.013263  14.373710  17.0  19.0  28.0  41.0  79.0
1st-4th        151.0  44.622517  14.929051  19.0  33.0  44.0  56.0  81.0
5th-6th        288.0  41.649306  14.754622  17.0  28.0  41.0  53.0  82.0
7th-8th        557.0  47.631957  15.737479  17.0  34.0  49.0  60.0  90.0
9th            455.0  40.303297  15.335754  17.0  28.0  38.0  53.0  90.0
Assoc-acdm    1008.0  37.286706  10.509755  19.0  29.0  36.0  44.0  90.0
Assoc-voc     1307.0  38.246366  11.181253  19.0  30.0  37.0  45.0  84.0
Bachelors     5044.0  38.641554  11.577566  19.0  29.0  37.0  46.0  90.0
Doctorate      375.0  47.130667  11.471727  24.0  39.0  47.0  54.0  80.0
HS-grad       9840.0  38.640955  13.067730  17.0  28.0  37.0  48.0  90.0
Masters       1627.0  43.740012  10.735356  18.0  36.0  43.0  50.0  90.0
Preschool       45.0  41.288889  15.175672  19.0  30.0  40.0  53.0  75.0
Prof-school    542.0  44.249077  11.428098  25.0  36.0  43.0  50.0  90.0
Some-college  6678.0  36.135370  13.073528  17.0  25.0  35.0  45.0  90.0

'Salaries of married and unmarried men:'

salary
<=50K    7052
>50K     5723
Name: count, dtype: int64

'Maximum number of hours a person works per week:'

99

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
0,0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K,39
1,1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K,35
2,2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K,27
3,3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K,43
4,4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,32556,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,38,United-States,<=50K,36
32557,32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,>50K,173
32558,32558,58,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,40,United-States,<=50K,40
32559,32559,22,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,20,United-States,<=50K,38
32560,32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,>50K,243

Mean and standard deviation of age:
>50K:
Mean: 43.95911028236548
Std: 10.269632835673844

<=50K:
Mean: 36.60806038668668
Std: 13.464631257161628

In [ ]:
# Select only numerical columns for correlation analysis
numerical_cols = sales_data.select_dtypes(include=['int64', 'float64'])

# Calculate the correlation matrix
correlation_matrix = numerical_cols.corr()

# Display the correlation matrix
display("Correlation matrix for numerical columns in sales_data:")
display(correlation_matrix)

'Correlation matrix for numerical columns in sales_data:'

                Unnamed: 0       age  hours-per-week  salary K$
Unnamed: 0        1.000000 -0.001126       -0.001890   0.000129
age              -0.001126  1.000000        0.101599   0.208203
hours-per-week   -0.001890  0.101599        1.000000   0.196378
salary K$         0.000129  0.208203        0.196378   1.000000